add options to handle base_url in manifest
gpac/gpac pull request #2920
Opened 2024-07-23 15:57 UTC by soheibthriber

Three possible case:
1) strip the base url
2) keep base url as it is
3) inject a relative path

2024-07-24 08:59 UTC, jeanlf requested changes

2024-07-24 08:59 UTC, jeanlf commented on src/filters/dmx_dash.c
> +		"- inject: inject local relative URL before BaseURL value specified by relative_url option.", GF_PROP_STRING, "false", "false|true|inject", GF_FS_ARG_HINT_EXPERT},
Could you please make this an enum (GF_PROP_UINT)  and not a string ?

2024-09-02 09:31 UTC, jeanlf requested changes

2024-09-02 09:31 UTC, jeanlf commented on src/filters/dmx_dash.c
> +        "- 2: inject local relative URL before BaseURL value specified by relative_url option.", GF_PROP_UINT, "0", "0|1|2", GF_FS_ARG_HINT_EXPERT},
could you use strip, keep and inject for enum names instead of 0,1 and 2 ?

2024-09-04 11:48 UTC, jeanlf requested changes

2024-09-04 11:48 UTC, jeanlf commented on src/filters/dmx_dash.c
> +
Could you please use capital, prefixed names for the values as we do in the rest of the code, e.g. BURL_KEEP,BURL_STRIP,BURL_INJECT

2024-11-06 18:40 UTC, rbouqueau commented
What is the status on this PR?

2024-11-08 10:19 UTC, jeanlf approved these changes

2024-11-08 10:19 UTC, merged

2024-11-08 10:19 UTC, jeanlf commented
thanks!